## WiSHFUL Agent config file

agent_info:
  name: 'agent_123'
  info: 'agent_info'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eth0", "groupName":"wishful_1234"}

  lora:
      module : module_lora
      class_name : LoraModule
      interfaces : ['eth0']

